api/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .rest_views import *
from rest_framework.routers import SimpleRouter

route = SimpleRouter()
route.register(r'rest', RestView)

app_name = 'api'
urlpatterns = [
  path('', views.index, name='index'),
  path('getuser/', views.get_login_user, name="getUser"),
  path('logout/', views.logout, name='logout'),
  path('login', views.login, name='login'),
  path('test', views.test, name='test'),
  path('getdata', views.get_all, name='getData'),
  path('register', views.register, name="register"),
  path('getpermission', views.get_permission, name='permission'),
  path('delete', views.delete_record, name="delete"),
  path('add', views.add_data, name="add_data"),
  path('update', views.update_data, name="update_data"),
  path('search', views.searchData, name="serch_data"),
] + route.urls

miniProject/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'miniProject'
urlpatterns = [
    path('', views.index, name='home'),
    path('generateData/', views.temp, name='temp'),
    path('login/',views.login, name="login"),
    path('loginAuthen/',views.login_authen, name="loginAuthen"),
    path('logout/',views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('registerSubmit/', views.register_submit, name="registerSubmit"),
    path('get1/', views.get_static_pop_mac, name='get1'),
    path('get2/', views.get_dynamic_pop_mac, name='get2'),
    path('<int:_id>/update', views.update_data, name = "update_data"),
    path('<int:_id>/updateSubmit', views.update_submit, name = "update_submit"),
    path('<int:_id>/delete', views.delete_data, name = "delete_data"),
    path('add/', views.add_data, name = "add_data"),
    path('addsubmit/', views.add_submit, name = "add_submit"),
    path('changePage/', views.change_page, name = "change_page"),
    path('test/', views.test, name = "test"),
]

myProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('home/', include('miniProject.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    
    
]

miniProject/models.py
from django.db import models
from django.forms import CharField

# Create your models here.
class SampleData(models.Model):
    ip = models.CharField(max_length=100, default="10.41.2.28")
    hostname = models.CharField(max_length=100, default="HNIB03405HW50")
    branch = models.CharField(max_length=100, default="BTHT1")
    zone = models.IntegerField(default=1)
    pop = models.CharField(max_length=100, default="HNIB034")
    type = models.CharField(max_length=100, default="HUAWEI")
    function = models.CharField(max_length=100, default="SW-FTI-BB")
    model = models.CharField(max_length=100, default="HW50")
    province = models.CharField(max_length=100, default="HNI")
    total_mac = models.IntegerField(default=35)
    smart_link = models.BooleanField(default=False)
    sep = models.BooleanField(default=False)
    stack = models.BooleanField(default=False)
    number_of_pop_tail = models.IntegerField(default=0)
    patch_ver = models.CharField(max_length=100, default="s5720si-v200r011sph007")
    patch_state = models.CharField(max_length=100, default="running")
    software_ver = models.CharField(max_length=100, default="S5720 V200R011C10SPC600")
    switch_type = models.CharField(max_length=100, default="S5720-28X-")


    def __str__(self):
        return self.ip

miniProject/views.py
from os import popen
from django.http import HttpResponse, JsonResponse
from .models import SampleData
import random
from django.shortcuts import render, get_object_or_404, redirect
from .form import LoginForm  
from django.contrib.auth import authenticate, logout as auth_logout
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User, Group
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.db.models import Q
import math

@csrf_exempt
def test(request):
    data = SampleData.objects.filter(id = 780).values()
    return JsonResponse({"record": list(data)})

page = 1
pageChange = False
@csrf_exempt
def index(request):
    global pageChange
    global page
    if pageChange:
        pageChange = False
    else:
        page = 1
    data = SampleData.objects.filter()
    header = ['ID', 'IP', 'Hostname','Branch', 'Zone', 'Pop', 'Type', 'Function', 'Model', 'Province', 'Total MAC', 'Smart link', 'Sep', 'Stack', 'Number of pop tail', 'patch ver', 'patch state', 'software ver', 'switch type' ]
    if request.user.is_authenticated:
        notice = "User is logged in as %s with a role %s" % (request.user.username, request.user.groups.all()[0])
        group = request.user.groups.all()[0]
        max_page = math.ceil(len(data)/100)
        min = (page-1) * 100
        max = (len(data)) if (min + 100 > len(data)) else min + 100
        print(page)
        temp_data = []
        for i in range(min, max):
            temp_data.append(data[i])
        return render(request, 'miniProject/home.html', {'notice':notice, 'group' : str(group), 'data' : temp_data, 'header' : header, 'maxpage':max_page, 'page':page})
    else:
        notice = "User is not logged in :("
        return render(request, 'miniProject/home.html', {'notice':notice, 'group' : "group", 'data' : data, 'header':header, 'maxpage':0, 'page':page})

def change_page(request):
    global page
    global pageChange
    print(request.GET['page'])
    pageChange = True
    page = int(request.GET['page'])
    return redirect('/home')

def temp(request):
    for i in range(3000):
        mac = random.randint(0,10000)
        pop = random.randint(0,10)
        print(i, mac, pop)
        temp = SampleData(number_of_pop_tail = pop, total_mac = mac)
        temp.save()
    return HttpResponse("ok")

def login(request):
    return render(request, 'miniProject/login.html')

def login_authen(request):

    userLogin = authenticate(username=request.POST['username'], password=request.POST['password'])

    if userLogin is not None:
        auth_login(request, userLogin)
        return render(request, 'miniProject/loginResult.html')
    else:
        return render(request, 'miniProject/loginResult.html')
            

def logout(request):
    global page
    page = 1
    auth_logout(request)
    return render(request, 'miniProject/logout.html')

def register(request):
    return render(request, 'miniProject/register.html')

def register_submit(request):
    try:
        user = User.objects.create_user(request.POST['username'], request.POST['email'], request.POST['password'])
        group = Group.objects.get(name = request.POST['accountGroup'])
        user.save()
        user.groups.add(group)
        return redirect('/home/login')
    except:
        return render(request, "miniProject/registerResult.html")

@csrf_exempt
def get_static_pop_mac(request):
    data = SampleData.objects.filter(Q(total_mac__gte = 100) | Q(number_of_pop_tail__gte = 30)).values()
    print(type(data))
    return JsonResponse({"record": list(data)})

@csrf_exempt
def get_dynamic_pop_mac(request):
    print(request.GET['total_mac'])
    print(request.GET['number_of_pop_tail'])
    data = SampleData.objects.filter(total_mac = request.GET['total_mac'], number_of_pop_tail = request.GET['number_of_pop_tail']).values()
    print(type(data))
    return JsonResponse({"record": list(data)})

@csrf_exempt
def update_data(request, _id):
    data = SampleData.objects.get(id = _id)
    return render(request, "miniProject/update.html",{'data':data})

@csrf_exempt
def update_submit(request, _id):
    data = SampleData.objects.get(id = _id)

    data.hostname = request.POST['hostname']
    data.branch = request.POST['branch']
    data.zone = request.POST['zone']
    data.pop = request.POST['pop']
    data.type = request.POST['type']
    data.function = request.POST['function']
    data.model = request.POST['model']
    data.province = request.POST['province']
    data.itotal_macp = request.POST['total_mac']
    data.smart_link = request.POST['smart_link']
    data.sep = request.POST['sep']
    data.stack = request.POST['stack']
    data.number_of_pop_tail = request.POST['number_of_pop_tail']
    data.patch_ver = request.POST['patch_ver']
    data.patch_state = request.POST['patch_state']
    data.software_ver = request.POST['software_ver']
    data.switch_type = request.POST['switch_type']

    data.save()
    return redirect('/home')


@csrf_exempt
def delete_data(request, _id):
    data = SampleData.objects.get(id = _id)
    data.delete()
    return redirect('/home')

@csrf_exempt
def add_data(request):
    return render(request, "miniProject/add.html")

@csrf_exempt
def add_submit(request):
    data = SampleData()

    data.hostname = request.POST['hostname']
    data.branch = request.POST['branch']
    data.zone = request.POST['zone']
    data.pop = request.POST['pop']
    data.type = request.POST['type']
    data.function = request.POST['function']
    data.model = request.POST['model']
    data.province = request.POST['province']
    data.total_mac = request.POST['total_mac']
    data.smart_link = request.POST['smart_link']
    data.sep = request.POST['sep']
    data.stack = request.POST['stack']
    data.number_of_pop_tail = request.POST['number_of_pop_tail']
    data.patch_ver = request.POST['patch_ver']
    data.patch_state = request.POST['patch_state']
    data.software_ver = request.POST['software_ver']
    data.switch_type = request.POST['switch_type']

    data.save()
    return redirect('/home')

miniProject/templates/miniProject/add.html
<a href="/home">home</a>
<form action= "{% url 'miniProject:add_submit'  %}" method="post">
    {% csrf_token %}
    <h1>New Data</h1>
    
    <label for="ip">IP: </label>
    <input id="ip" type="text" name="ip" value="{{ data.ip }}">
    <br><br>

    <label for="hostname">Hostname: </label>
    <input id="hostname" type="text" name="hostname" value="{{ data.hostname }}">
    <br><br>

    <label for="branch">Branch: </label>
    <input id="branch" type="text" name="branch" value="{{ data.branch }}">
    <br><br>

    <label for="Zone">Zone: </label>
    <input id="Zone" type="number" name="zone" value="{{ data.zone }}">
    <br><br>

    <label for="pop">Pop: </label>
    <input id="pop" type="text" name="pop" value="{{ data.pop }}">
    <br><br>

    <label for="type">Type: </label>
    <input id="type" type="text" name="type" value="{{ data.type }}">
    <br><br>

    <label for="function">Function: </label>
    <input id="function" type="text" name="function" value="{{ data.function }}">
    <br><br>

    <label for="model">Model: </label>
    <input id="model" type="text" name="model" value="{{ data.model }}">
    <br><br>

    <label for="province">Province: </label>
    <input id="province" type="text" name="province" value="{{ data.province }}">
    <br><br>

    <label for="total_mac">Total MAC: </label>
    <input id="total_mac" type="number" name="total_mac" value="{{ data.total_mac }}">
    <br><br>


    <label for="smart_link">Smart Link:</label>
    <select name="smart_link" id="smart_link">
    {%if data.smart_link == 0 %}
        <option value= 1>True</option>
        <option value= 0 selected = "selected">False</option> 
     {% else %} 
        <option value= 1 selected = "selected">True</option>
        <option value= 0>False</option>
     {% endif %}
    </select>
    <br><br>

    <label for="sep">Sep:</label>
    <select name="sep" id="sep">
    {%if data.sep == 0 %}
        <option value= 1>True</option>
        <option value= 0 selected = "selected">False</option> 
     {% else %} 
        <option value= 1 selected = "selected">True</option>
        <option value= 0>False</option>
     {% endif %}
    </select>
    <br><br>

    <label for="stack">Stack:</label>
    <select name="stack" id="stack">
    {%if data.stack == 0 %}
        <option value= 1>True</option>
        <option value= 0 selected = "selected">False</option> 
     {% else %} 
        <option value= 1 selected = "selected">True</option>
        <option value= 0>False</option>
     {% endif %}
    </select>
    <br><br>

    <label for="number_of_pop_tail">Number of pop tail: </label>
    <input id="number_of_pop_tail" type="number" name="number_of_pop_tail" value="{{ data.number_of_pop_tail }}">
    <br><br>

    <label for="patch_ver">Patch version: </label>
    <input id="patch_ver" type="text" name="patch_ver" value="{{ data.patch_ver }}">
    <br><br>

    <label for="patch_state">Patch state: </label>
    <input id="patch_state" type="text" name="patch_state" value="{{ data.patch_state }}">
    <br><br>
    
    <label for="software_ver">Software version: </label>
    <input id="software_ver" type="text" name="software_ver" value="{{ data.software_ver }}">
    <br><br>

    <label for="switch_type">Switch type: </label>
    <input id="switch_type" type="text" name="switch_type" value="{{ data.switch_type }}">
    <br><br>

    <input type="submit" value="Save">
    

</form>

miniProject/templates/miniProject/home.html
<head>
    <style>
        .table {
           text-align: center;
           border: 1px solid black;
           border-collapse: collapse;
           width : 100%;
        }
        td,th,tr {
           text-align: center;
           border: 1px solid black;
        }
        th {
            background-color: rgba(162, 162, 162, 0.956);
        }
    </style>
</head>
<h1>Home Page</h1>
{% csrf_token %}

<p>{{notice}}</p>

{%if request.user.is_authenticated %}
<form action="/home/changePage/" style="display: inline-block">

    <label for="page">Page (1 - {{maxpage}}): </label>
    <input id="page" type="number" name="page" value="{{page}}">
    <input type="submit" value="Go" />
</form>

<form action="/home/logout/" style="display: inline-block">

    <input type="submit" value="Logout" />
</form>
<br><p>Page {{page}}</p>
{%if group == "KTHT" %}
<form style="display: inline-block" action="/home/add">
    <input type="submit" value="Add" />
</form>

<table class="table">
    <thead>
        <tr>
            {% for k in header %}
            <th>{{k}}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for e in data %}
            <tr>
                <td>{{e.id}}</td>
                <td>{{e.ip}}</td>
                <td>{{e.hostname}}</td>
                <td>{{e.branch}}</td>
                <td>{{e.zone}}</td>
                <td>{{e.pop}}</td>
                <td>{{e.type}}</td>
                <td>{{e.function}}</td>
                <td>{{e.model}}</td>
                <td>{{e.province}}</td>
                <td>{{e.total_mac}}</td>
                <td>{{e.smart_link}}</td>
                <td>{{e.sep}}</td>
                <td>{{e.stack}}</td>
                <td>{{e.number_of_pop_tail}}</td>
                <td>{{e.patch_ver}}</td>
                <td>{{e.patch_state}}</td>
                <td>{{e.software_ver}}</td>
                <td>{{e.switch_type}}</td>
                <td><a href="{% url 'miniProject:update_data' e.id %}">edit</a></td>
                <td><a href="{% url 'miniProject:delete_data' e.id %}">delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% else %} 

{{data.page.id}}
<table class="table">
    <thead>
        <tr>
            {% for k in header %}
            <th>{{k}}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for e in data %}
            <tr>
                <td>{{e.id}}</td>
                <td>{{e.ip}}</td>
                <td>{{e.hostname}}</td>
                <td>{{e.branch}}</td>
                <td>{{e.zone}}</td>
                <td>{{e.pop}}</td>
                <td>{{e.type}}</td>
                <td>{{e.function}}</td>
                <td>{{e.model}}</td>
                <td>{{e.province}}</td>
                <td>{{e.total_mac}}</td>
                <td>{{e.smart_link}}</td>
                <td>{{e.sep}}</td>
                <td>{{e.stack}}</td>
                <td>{{e.number_of_pop_tail}}</td>
                <td>{{e.patch_ver}}</td>
                <td>{{e.patch_state}}</td>
                <td>{{e.software_ver}}</td>
                <td>{{e.switch_type}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% else %}
<form action="/home/login/">
    <input type="submit" value="login" />
</form>
{% endif %}

miniProject/templates/miniProject/login.html
<a href="/home">home</a>
<form action= "{% url 'miniProject:loginAuthen' %}" method="post">
    {% csrf_token %}
    <h1>Login</h1>
    
    <label for="username">Username: </label>
    <input id="username" type="text" name="username" value="{{ username }}">
    <br><br>
    <label for="password">Password: </label>
    <input id="password" type="password" name="password" value="{{ password }}">
    <input type="submit" value="Login">

</form>

<form action="/home/register/">
    <input type="submit" value="Register" />
</form>

miniProject/templates/miniProject/loginResult.html
<h1>Login</h1>
{% csrf_token %}


{%if request.user.is_authenticated %}
<p>You are logged in as {{request.user.username}}</p>
<form action="/home/">
    <input type="submit" value="Back to home" />
</form>{% else %}
<p>Wrong username and password. You are not logged in</p>
<form action="/home/login/">
    <input type="submit" value="Back to login" />
</form>
{% endif %}

miniProject/templates/miniProject/logout.html
<h1>Logout</h1>
{% csrf_token %}


<p>You are logged out</p>
<form action="/home">
    <input type="submit" value="Back to home" />
</form>

miniProject/templates/miniProject/register.html
<a href="/home">home</a>
<form action= "{% url 'miniProject:registerSubmit' %}" method="post">
    {% csrf_token %}
    <h1>Register</h1>
    
    <label for="username">Username: </label>
    <input id="username" type="text" name="username" value="{{ username }}">
    <br><br>
    <label for="email">Email: </label>
    <input id="email" type="text" name="email" value="{{ email }}">
    <br><br>
    <label for="password">Password: </label>
    <input id="password" type="password" name="password" value="{{ password }}">
    <input type="submit" value="Register">
    <br><br>
    <label for="acountGroup">Type of account:</label>
    <select name="accountGroup" id="accountGroup">
      <option value="KTHT">KTHT</option>
      <option value="CNT">CNT</option>    
    </select>
    <br><br>

</form>

  

<form action="/home/login/">
    <input type="submit" value="Login" />
</form>

miniProject/templates/miniProject/registerResult.html
<a href="/home">home</a>
<h1>Register</h1>
{% csrf_token %}


<p>Your register is failed</p>
<form action="/home/register">
    <input type="submit" value="Back to register" />
</form>

miniProject/templates/miniProject/update.html
<a href="/home">home</a>
<form action= "{% url 'miniProject:update_submit' data.id  %}" method="post">
    {% csrf_token %}
    <h1>Update</h1>
    
    <label for="ip">IP: </label>
    <input id="ip" type="text" name="ip" value="{{ data.ip }}">
    <br><br>

    <label for="hostname">Hostname: </label>
    <input id="hostname" type="text" name="hostname" value="{{ data.hostname }}">
    <br><br>

    <label for="branch">Branch: </label>
    <input id="branch" type="text" name="branch" value="{{ data.branch }}">
    <br><br>

    <label for="Zone">Zone: </label>
    <input id="Zone" type="number" name="zone" value="{{ data.zone }}">
    <br><br>

    <label for="pop">Pop: </label>
    <input id="pop" type="text" name="pop" value="{{ data.pop }}">
    <br><br>

    <label for="type">Type: </label>
    <input id="type" type="text" name="type" value="{{ data.type }}">
    <br><br>

    <label for="function">Function: </label>
    <input id="function" type="text" name="function" value="{{ data.function }}">
    <br><br>

    <label for="model">Model: </label>
    <input id="model" type="text" name="model" value="{{ data.model }}">
    <br><br>

    <label for="province">Province: </label>
    <input id="province" type="text" name="province" value="{{ data.province }}">
    <br><br>

    <label for="total_mac">Total MAC: </label>
    <input id="total_mac" type="number" name="total_mac" value="{{ data.total_mac }}">
    <br><br>


    <label for="smart_link">Smart Link:</label>
    <select name="smart_link" id="smart_link">
    {%if data.smart_link == 0 %}
        <option value= 1>True</option>
        <option value= 0 selected = "selected">False</option> 
     {% else %} 
        <option value= 1 selected = "selected">True</option>
        <option value= 0>False</option>
     {% endif %}
    </select>
    <br><br>

    <label for="sep">Sep:</label>
    <select name="sep" id="sep">
    {%if data.sep == 0 %}
        <option value= 1>True</option>
        <option value= 0 selected = "selected">False</option> 
     {% else %} 
        <option value= 1 selected = "selected">True</option>
        <option value= 0>False</option>
     {% endif %}
    </select>
    <br><br>

    <label for="stack">Stack:</label>
    <select name="stack" id="stack">
    {%if data.stack == 0 %}
        <option value= 1>True</option>
        <option value= 0 selected = "selected">False</option> 
     {% else %} 
        <option value= 1 selected = "selected">True</option>
        <option value= 0>False</option>
     {% endif %}
    </select>
    <br><br>

    <label for="number_of_pop_tail">Number of pop tail: </label>
    <input id="number_of_pop_tail" type="number" name="number_of_pop_tail" value="{{ data.number_of_pop_tail }}">
    <br><br>

    <label for="patch_ver">Patch version: </label>
    <input id="patch_ver" type="text" name="patch_ver" value="{{ data.patch_ver }}">
    <br><br>

    <label for="patch_state">Patch state: </label>
    <input id="patch_state" type="text" name="patch_state" value="{{ data.patch_state }}">
    <br><br>
    
    <label for="software_ver">Software version: </label>
    <input id="software_ver" type="text" name="software_ver" value="{{ data.software_ver }}">
    <br><br>

    <label for="switch_type">Switch type: </label>
    <input id="switch_type" type="text" name="switch_type" value="{{ data.switch_type }}">
    <br><br>

    <input type="submit" value="Save">
    

</form>